// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMedia.Infrastructure.Data;

#nullable disable

namespace SocialMedia.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SocialMediaDbContext))]
    [Migration("20260122084506_SeededPosts")]
    partial class SeededPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialMedia.Infrastructure.Data.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = "post-01-9f1b4d8a-21c0-4f5c-b102-a001",
                            Content = "Started rebuilding my backend architecture today.",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "post-02-7c2a5d11-2e90-4bcb-a901-a002",
                            Content = "React hooks finally make sense.",
                            CreatedAt = new DateTime(2026, 1, 1, 9, 15, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902"
                        },
                        new
                        {
                            Id = "post-03-b81a7a29-0b8c-4a3b-b621-a003",
                            Content = "Designing a fresh dark theme UI 🌙",
                            CreatedAt = new DateTime(2026, 1, 1, 10, 40, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/3.jpg",
                            UserId = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903"
                        },
                        new
                        {
                            Id = "post-04-21f7ac19-91c2-48bb-b812-a004",
                            Content = "Learning penetration testing basics.",
                            CreatedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "c91e9189-281f-48c3-b8ad-1b20f4f10104"
                        },
                        new
                        {
                            Id = "post-05-3d71a8b4-7731-4b42-93b2-a005",
                            Content = "New illustration finished today 🎨",
                            CreatedAt = new DateTime(2026, 1, 1, 13, 25, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/5.jpg",
                            UserId = "da3a7cb3-5d90-45d2-83d9-9f8a2d92a105"
                        },
                        new
                        {
                            Id = "post-06-41bc8c90-d241-4aa4-9921-a006",
                            Content = "Docker containers saved my sanity.",
                            CreatedAt = new DateTime(2026, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "b9f4c2d1-4d94-4ff6-87aa-0ccf933bf106"
                        },
                        new
                        {
                            Id = "post-07-19f7d901-8f62-4b98-8211-a007",
                            Content = "Experimenting with game physics today.",
                            CreatedAt = new DateTime(2026, 1, 2, 9, 30, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/7.jpg",
                            UserId = "e38db6c0-7b92-4f0f-b76a-d7b7f1aab107"
                        },
                        new
                        {
                            Id = "post-08-771a9d44-6f11-4d55-b341-a008",
                            Content = "Exams week again 😭",
                            CreatedAt = new DateTime(2026, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108"
                        },
                        new
                        {
                            Id = "post-09-5a6a7b28-3810-4d6a-9c81-a009",
                            Content = "Publishing my next tech article soon.",
                            CreatedAt = new DateTime(2026, 1, 2, 13, 45, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/9.jpg",
                            UserId = "c6fdb72c-65b1-42df-bd03-4a3ff37f6109"
                        },
                        new
                        {
                            Id = "post-10-9912a83a-2489-4f7b-9a31-a010",
                            Content = "Analytics dashboards are addictive.",
                            CreatedAt = new DateTime(2026, 1, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110"
                        },
                        new
                        {
                            Id = "post-11-84b7d312-fb20-41ad-9012-a011",
                            Content = "Mobile app memory usage finally optimized.",
                            CreatedAt = new DateTime(2026, 1, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "bf8ad623-ff4a-44b3-b2b2-109cbe8a2111"
                        },
                        new
                        {
                            Id = "post-12-27b7f981-21a0-4db6-81f1-a012",
                            Content = "QA automation saves weeks of work.",
                            CreatedAt = new DateTime(2026, 1, 3, 10, 10, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "2df3b7c4-29c2-41b2-b2cb-51c8f20d8112"
                        },
                        new
                        {
                            Id = "post-13-fbc38d22-7b2a-4c51-a819-a013",
                            Content = "Java memory tuning is underrated.",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 40, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "4b46a84d-21a3-44db-9d2f-68c2f51f3113"
                        },
                        new
                        {
                            Id = "post-14-91d72d19-2ab0-4e18-9f10-a014",
                            Content = "Reading about smart contracts today.",
                            CreatedAt = new DateTime(2026, 1, 3, 13, 20, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "5d7e09fa-b71a-44c5-9e1f-9b4e4b09f114"
                        },
                        new
                        {
                            Id = "post-15-31aa20fa-1e0c-4a4f-902a-a015",
                            Content = "Sprint planning done ✔️",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115"
                        },
                        new
                        {
                            Id = "post-16-ff2b91d0-7e42-46ad-a0f9-a016",
                            Content = "Cloud cost optimization is painful.",
                            CreatedAt = new DateTime(2026, 1, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "aa9aef99-4d6f-4b7a-b3a7-0b2b8d731116"
                        },
                        new
                        {
                            Id = "post-17-62cbd91a-f61e-4ef7-93fa-a017",
                            Content = "Hiring developers is harder than coding.",
                            CreatedAt = new DateTime(2026, 1, 4, 10, 30, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "bbcfb1c7-d4a6-46fa-a9cc-5c9df8d07117"
                        },
                        new
                        {
                            Id = "post-18-1187a1df-4f42-4b02-b1f2-a018",
                            Content = "Pitch deck is almost ready 🚀",
                            CreatedAt = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "d14dc8ad-3b9f-4f1a-b50a-82d0c3e71118"
                        },
                        new
                        {
                            Id = "post-19-bc72fa01-3b22-4a83-9b41-a019",
                            Content = "JWT refresh tokens implemented.",
                            CreatedAt = new DateTime(2026, 1, 5, 9, 10, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01"
                        },
                        new
                        {
                            Id = "post-20-8c29f21a-5b81-47f2-a90c-a020",
                            Content = "Finally mastered CSS grid.",
                            CreatedAt = new DateTime(2026, 1, 5, 10, 45, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902"
                        },
                        new
                        {
                            Id = "post-21-37c29fa1-6e41-4012-a2b2-a021",
                            Content = "Minimal UI beats flashy UI.",
                            CreatedAt = new DateTime(2026, 1, 5, 12, 20, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903"
                        },
                        new
                        {
                            Id = "post-22-d31a8a41-ef02-42f7-8c3a-a022",
                            Content = "Sketching ideas for next artwork.",
                            CreatedAt = new DateTime(2026, 1, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/22.jpg",
                            UserId = "da3a7cb3-5d90-45d2-83d9-9f8a2d92a105"
                        },
                        new
                        {
                            Id = "post-23-51c9b122-19fa-48e3-8db1-a023",
                            Content = "CI/CD pipelines should be boring.",
                            CreatedAt = new DateTime(2026, 1, 5, 16, 10, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "b9f4c2d1-4d94-4ff6-87aa-0ccf933bf106"
                        },
                        new
                        {
                            Id = "post-24-1a8f7e21-d22b-4c4e-a190-a024",
                            Content = "Procedural terrain generation test.",
                            CreatedAt = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Image = "/posts/24.jpg",
                            UserId = "e38db6c0-7b92-4f0f-b76a-d7b7f1aab107"
                        },
                        new
                        {
                            Id = "post-25-91c2df11-cc81-41fa-94b2-a025",
                            Content = "Coffee count today: 5 ☕",
                            CreatedAt = new DateTime(2026, 1, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108"
                        },
                        new
                        {
                            Id = "post-26-62adf91b-421a-421f-b912-a026",
                            Content = "Tech blogging consistency is hard.",
                            CreatedAt = new DateTime(2026, 1, 6, 13, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "c6fdb72c-65b1-42df-bd03-4a3ff37f6109"
                        },
                        new
                        {
                            Id = "post-27-9a81df21-1910-4d41-a401-a027",
                            Content = "Conversion metrics improved by 12%.",
                            CreatedAt = new DateTime(2026, 1, 6, 15, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110"
                        },
                        new
                        {
                            Id = "post-28-2bc81df9-81fa-4f10-bd91-a028",
                            Content = "Flutter vs React Native debate continues.",
                            CreatedAt = new DateTime(2026, 1, 6, 17, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "bf8ad623-ff4a-44b3-b2b2-109cbe8a2111"
                        },
                        new
                        {
                            Id = "post-29-44bd9a01-2f10-4b72-b910-a029",
                            Content = "Regression tests passed ✅",
                            CreatedAt = new DateTime(2026, 1, 6, 18, 30, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "2df3b7c4-29c2-41b2-b2cb-51c8f20d8112"
                        },
                        new
                        {
                            Id = "post-30-2f8a91c2-18b4-4db9-b120-a030",
                            Content = "Refactoring legacy code feels great.",
                            CreatedAt = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            UserId = "4b46a84d-21a3-44db-9d2f-68c2f51f3113"
                        });
                });

            modelBuilder.Entity("SocialMedia.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1c7a44e8-6c82-4a51-8e77-15bdfd5b8a01",
                            Avatar = "/avatars/u1.png",
                            Bio = "Backend developer • ASP.NET • Linux",
                            CreatedAt = new DateTime(2024, 12, 1, 9, 10, 0, 0, DateTimeKind.Utc),
                            Email = "bozhidar@example.com",
                            Username = "bozhidar"
                        },
                        new
                        {
                            Id = "a6a7d7a9-43e5-4ad1-9c89-41287b4d3902",
                            Avatar = "/avatars/u2.png",
                            Bio = "Frontend dev • React",
                            CreatedAt = new DateTime(2024, 12, 3, 11, 20, 0, 0, DateTimeKind.Utc),
                            Email = "alex@example.com",
                            Username = "alex"
                        },
                        new
                        {
                            Id = "f52b5f4d-8c4e-4b3a-91fd-3c79cdb1c903",
                            Avatar = "/avatars/u3.png",
                            Bio = "UI / UX designer",
                            CreatedAt = new DateTime(2024, 12, 5, 15, 45, 0, 0, DateTimeKind.Utc),
                            Email = "maria@example.com",
                            Username = "maria"
                        },
                        new
                        {
                            Id = "c91e9189-281f-48c3-b8ad-1b20f4f10104",
                            Avatar = "/avatars/u4.png",
                            Bio = "Cybersecurity student",
                            CreatedAt = new DateTime(2024, 12, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nikola@example.com",
                            Username = "nikola"
                        },
                        new
                        {
                            Id = "da3a7cb3-5d90-45d2-83d9-9f8a2d92a105",
                            Avatar = "/avatars/u5.png",
                            Bio = "Digital artist",
                            CreatedAt = new DateTime(2024, 12, 7, 12, 40, 0, 0, DateTimeKind.Utc),
                            Email = "elena@example.com",
                            Username = "elena"
                        },
                        new
                        {
                            Id = "b9f4c2d1-4d94-4ff6-87aa-0ccf933bf106",
                            Avatar = "/avatars/u6.png",
                            Bio = "DevOps • Docker • Kubernetes",
                            CreatedAt = new DateTime(2024, 12, 9, 8, 10, 0, 0, DateTimeKind.Utc),
                            Email = "ivan@example.com",
                            Username = "ivan"
                        },
                        new
                        {
                            Id = "e38db6c0-7b92-4f0f-b76a-d7b7f1aab107",
                            Avatar = "/avatars/u7.png",
                            Bio = "Game developer",
                            CreatedAt = new DateTime(2024, 12, 10, 18, 30, 0, 0, DateTimeKind.Utc),
                            Email = "petar@example.com",
                            Username = "petar"
                        },
                        new
                        {
                            Id = "17a7f919-62b3-4b1b-94bb-8cf80b8aa108",
                            Avatar = "/avatars/u8.png",
                            Bio = "Computer science student",
                            CreatedAt = new DateTime(2024, 12, 11, 13, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sofia@example.com",
                            Username = "sofia"
                        },
                        new
                        {
                            Id = "c6fdb72c-65b1-42df-bd03-4a3ff37f6109",
                            Avatar = "/avatars/u9.png",
                            Bio = "Tech blogger",
                            CreatedAt = new DateTime(2024, 12, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            Email = "george@example.com",
                            Username = "george"
                        },
                        new
                        {
                            Id = "88dfb5b0-12c2-42d6-bb0d-9eaa9e9a3110",
                            Avatar = "/avatars/u10.png",
                            Bio = "Marketing specialist",
                            CreatedAt = new DateTime(2024, 12, 14, 9, 20, 0, 0, DateTimeKind.Utc),
                            Email = "victoria@example.com",
                            Username = "victoria"
                        },
                        new
                        {
                            Id = "bf8ad623-ff4a-44b3-b2b2-109cbe8a2111",
                            Avatar = "/avatars/u11.png",
                            Bio = "Mobile developer",
                            CreatedAt = new DateTime(2024, 12, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            Email = "daniel@example.com",
                            Username = "daniel"
                        },
                        new
                        {
                            Id = "2df3b7c4-29c2-41b2-b2cb-51c8f20d8112",
                            Avatar = "/avatars/u12.png",
                            Bio = "QA engineer",
                            CreatedAt = new DateTime(2024, 12, 16, 11, 10, 0, 0, DateTimeKind.Utc),
                            Email = "teodora@example.com",
                            Username = "teodora"
                        },
                        new
                        {
                            Id = "4b46a84d-21a3-44db-9d2f-68c2f51f3113",
                            Avatar = "/avatars/u13.png",
                            Bio = "Java developer",
                            CreatedAt = new DateTime(2024, 12, 17, 10, 10, 0, 0, DateTimeKind.Utc),
                            Email = "martin@example.com",
                            Username = "martin"
                        },
                        new
                        {
                            Id = "5d7e09fa-b71a-44c5-9e1f-9b4e4b09f114",
                            Avatar = "/avatars/u14.png",
                            Bio = "Blockchain enthusiast",
                            CreatedAt = new DateTime(2024, 12, 18, 19, 30, 0, 0, DateTimeKind.Utc),
                            Email = "kaloyan@example.com",
                            Username = "kaloyan"
                        },
                        new
                        {
                            Id = "82b1e839-f782-4c16-a1c2-2f8f1a2a5115",
                            Avatar = "/avatars/u15.png",
                            Bio = "Product manager",
                            CreatedAt = new DateTime(2024, 12, 19, 8, 50, 0, 0, DateTimeKind.Utc),
                            Email = "irina@example.com",
                            Username = "irina"
                        },
                        new
                        {
                            Id = "aa9aef99-4d6f-4b7a-b3a7-0b2b8d731116",
                            Avatar = "/avatars/u16.png",
                            Bio = "Cloud engineer",
                            CreatedAt = new DateTime(2024, 12, 20, 12, 10, 0, 0, DateTimeKind.Utc),
                            Email = "stefan@example.com",
                            Username = "stefan"
                        },
                        new
                        {
                            Id = "bbcfb1c7-d4a6-46fa-a9cc-5c9df8d07117",
                            Avatar = "/avatars/u17.png",
                            Bio = "HR & recruiting",
                            CreatedAt = new DateTime(2024, 12, 21, 14, 15, 0, 0, DateTimeKind.Utc),
                            Email = "nadya@example.com",
                            Username = "nadya"
                        },
                        new
                        {
                            Id = "d14dc8ad-3b9f-4f1a-b50a-82d0c3e71118",
                            Avatar = "/avatars/u18.png",
                            Bio = "Startup founder",
                            CreatedAt = new DateTime(2024, 12, 22, 17, 40, 0, 0, DateTimeKind.Utc),
                            Email = "rado@example.com",
                            Username = "rado"
                        });
                });

            modelBuilder.Entity("SocialMedia.Infrastructure.Data.Models.Post", b =>
                {
                    b.HasOne("SocialMedia.Infrastructure.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
